theme: jekyll-theme-slate

title: FVUO's PhD

description: Some resources from my time as a PhD student.  I am working on translating Constraint Satisfaction Problems into Boolean SAT problems with the help of machine learning to choose the best encoding.
